### ISSUE TITLE
Why always Connection refused。。。

### ISSUE THREAD

**Issue by lizhaoch** [rberrelleza/jitsi-docker#1]
SEVERE: [32] org.jitsi.meet.ComponentMain.call().278 java.net.ConnectException: Connection refused (Connection refused), host:10.41.12.15, port:5347
org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused (Connection refused)
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:272)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:151)

**Comment by lizhaoch** [comment]
open a chatroom，backend will throw this log， jvb.log

**Comment by imainetti** [comment]
same problem here
